### ISSUE TITLE
Profile patch validation error 

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group6#347]
## About

I am trying to patch the user profile with the below request: 
![patchreq](https://user-images.githubusercontent.com/9639399/33229306-88f0161e-d1dd-11e7-9ea6-5e40b3134c59.png)

However, I am getting Validation error but I don't know why since it is not defined.

![patchres](https://user-images.githubusercontent.com/9639399/33229305-88cc8ce4-d1dd-11e7-9af6-b775fbc5a366.png)

**Comment by gokceuludogan** [comment]
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imdva2NldWx1ZG9nYW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJnb2tjZXVsdWRvZ2FuIiwiZXhwIjoxNTE0MTg5MTgzLCJ1c2VyX2lkIjoxMH0.GaLirbVkUDgsdAVAbkRV_FsQ9PlJQrQSyf2iedpKAQY
Content-Length: 284
Content-Type: application/json
User-Agent: runscope/0.1
BODY 

{
"profile": {
"interests": [
{
"label": "Person of Interest",
"description": "television crime drama series by Jonathan Nolan",
"url": "https://www.wikidata.org/wiki/Q564345"
},
{
"label": "Fringe",
"description": "American science fiction television series",
"url": "//www.wikidata.org/wiki/Q3815"
}
]
}
}

**Comment by yhkalayci** [comment]
The reasons for getting this error are:
- given URL is not valid in the second tag
- a backend bug: using serializer.ValidationError instead of serializers.ValidationError

An important note: If you would like to update some fields of a tag, you must do it with using patch request to /tags/<id>. You can not update description or URL field with using this post request since it only looks the label if the tag has already added to the system.
